package protocols

import org.jsoup.Jsoup
import scalaj.http.{Http, HttpOptions}

object AutoGenerateDocType extends App {

  val APIAddress = "http://localhost:9004/add-doctor-type"
  getDoctype()

  def getDoctype(): Unit = {
    val doc = Jsoup.connect("https://www.bioexplorer.net/types-of-doctors/").get
    doc.body().getElementsByClass("toc_list").tagName("li").forEach { item =>
      item.getElementsByTag("ul").forEach { ul =>
        ul.children().forEach { li =>
          val el = li.text().replaceAll("\\d{1,2}[.]\\W", "")
          val data = s"""{"doctorType": "$el"}"""
          println(s"element: $el")
          if (el != "Top 10 BEST Colleges For ObGyn") {
            Http(s"$APIAddress").postData(data)
              .header("Content-Type", "application/json")
              .header("Charset", "UTF-8")
              .option(HttpOptions.readTimeout(10000)).asString.body
          }
        }
      }
    }
  }

}
